version: '3.8'

services:
  redis:
    image: redis:latest  
    container_name: mail-robot-redis-dev
    restart: on-failure 
    ports:
      - "6379:6379" 
    environment:
      - REDIS_PASSWORD=  

    command: redis-server --appendonly no

  mysql:
    image: mysql:8.0
    container_name: mail-robot-mysql-dev
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_DATABASE: rag_hyde 
    command: --default-authentication-plugin=mysql_native_password
    # 不挂载数据卷，容器销毁后数据丢弃（开发环境用）

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mail-robot-rabbitmq-dev
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"